import 'exercise_catalog_item.dart';

const List<ExerciseCatalogItem> exerciseCatalog = [
  ExerciseCatalogItem(
    id: 'bench_press_barbell',
    name: 'Жим штанги лёжа',
    muscleGroup: 'Грудь',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['жим лежа', 'bench press'],
  ),
  ExerciseCatalogItem(
    id: 'bench_press_dumbbell',
    name: 'Жим гантелей лёжа',
    muscleGroup: 'Грудь',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['жим гантелей лежа', 'dumbbell bench press'],
  ),
  ExerciseCatalogItem(
    id: 'incline_barbell_press',
    name: 'Жим на наклонной скамье',
    muscleGroup: 'Грудь',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['наклонный жим', 'incline bench press'],
  ),
  ExerciseCatalogItem(
    id: 'incline_dumbbell_press',
    name: 'Жим гантелей на наклонной скамье',
    muscleGroup: 'Грудь',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['жим гантелей incline', 'incline dumbbell press'],
  ),
  ExerciseCatalogItem(
    id: 'push_ups',
    name: 'Отжимания',
    muscleGroup: 'Грудь',
    equipment: 'Без оборудования',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['push ups', 'push-ups'],
  ),
  ExerciseCatalogItem(
    id: 'dips',
    name: 'Отжимания на брусьях',
    muscleGroup: 'Грудь',
    equipment: 'Брусья',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['брусья', 'dips'],
  ),
  ExerciseCatalogItem(
    id: 'dumbbell_fly',
    name: 'Разводка гантелей лёжа',
    muscleGroup: 'Грудь',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['разведения гантелей лежа', 'dumbbell fly'],
  ),
  ExerciseCatalogItem(
    id: 'cable_crossover',
    name: 'Кроссовер',
    muscleGroup: 'Грудь',
    equipment: 'Кроссовер',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['crossover', 'cable crossover'],
  ),
  ExerciseCatalogItem(
    id: 'pec_deck',
    name: 'Сведение рук в тренажёре',
    muscleGroup: 'Грудь',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['бабочка', 'pec deck'],
  ),
  ExerciseCatalogItem(
    id: 'pullover',
    name: 'Пуловер',
    muscleGroup: 'Грудь',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['pullover'],
  ),
  ExerciseCatalogItem(
    id: 'pull_ups',
    name: 'Подтягивания',
    muscleGroup: 'Спина',
    equipment: 'Турник',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['pull ups', 'pull-ups'],
  ),
  ExerciseCatalogItem(
    id: 'barbell_row',
    name: 'Тяга штанги в наклоне',
    muscleGroup: 'Спина',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['barbell row'],
  ),
  ExerciseCatalogItem(
    id: 'one_arm_dumbbell_row',
    name: 'Тяга гантели одной рукой',
    muscleGroup: 'Спина',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['тяга гантели в наклоне', 'one arm dumbbell row'],
  ),
  ExerciseCatalogItem(
    id: 'lat_pulldown',
    name: 'Тяга верхнего блока',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['lat pulldown'],
  ),
  ExerciseCatalogItem(
    id: 'seated_cable_row',
    name: 'Тяга горизонтального блока',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['горизонтальная тяга', 'seated cable row'],
  ),
  ExerciseCatalogItem(
    id: 'deadlift',
    name: 'Становая тяга',
    muscleGroup: 'Спина',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['deadlift'],
  ),
  ExerciseCatalogItem(
    id: 'romanian_deadlift',
    name: 'Румынская тяга',
    muscleGroup: 'Ноги',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['рдл', 'romanian deadlift'],
  ),
  ExerciseCatalogItem(
    id: 'hyperextension',
    name: 'Гиперэкстензия',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['hyperextension'],
  ),
  ExerciseCatalogItem(
    id: 'shrugs',
    name: 'Шраги',
    muscleGroup: 'Спина',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['shrugs'],
  ),
  ExerciseCatalogItem(
    id: 't_bar_row',
    name: 'Тяга Т-грифа',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['t-bar row', 't bar row'],
  ),
  ExerciseCatalogItem(
    id: 'straight_arm_pulldown',
    name: 'Тяга прямыми руками',
    muscleGroup: 'Спина',
    equipment: 'Кроссовер',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['straight arm pulldown'],
  ),
  ExerciseCatalogItem(
    id: 'good_morning',
    name: 'Наклоны со штангой',
    muscleGroup: 'Спина',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['good morning', 'гуд морнинг'],
  ),
  ExerciseCatalogItem(
    id: 'shoulder_press',
    name: 'Жим штанги стоя',
    muscleGroup: 'Плечи',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['жим над головой', 'overhead press', 'ohp'],
  ),
  ExerciseCatalogItem(
    id: 'seated_dumbbell_shoulder_press',
    name: 'Жим гантелей сидя',
    muscleGroup: 'Плечи',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['dumbbell shoulder press'],
  ),
  ExerciseCatalogItem(
    id: 'military_press',
    name: 'Армейский жим',
    muscleGroup: 'Плечи',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['military press'],
  ),
  ExerciseCatalogItem(
    id: 'lateral_raise',
    name: 'Махи гантелями в стороны',
    muscleGroup: 'Плечи',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['разведения гантелей в стороны', 'lateral raise'],
  ),
  ExerciseCatalogItem(
    id: 'front_raise',
    name: 'Махи гантелями перед собой',
    muscleGroup: 'Плечи',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['подъём гантелей перед собой', 'front raise'],
  ),
  ExerciseCatalogItem(
    id: 'reverse_fly',
    name: 'Обратные махи',
    muscleGroup: 'Плечи',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['обратная разводка', 'reverse fly'],
  ),
  ExerciseCatalogItem(
    id: 'upright_row',
    name: 'Тяга штанги к подбородку',
    muscleGroup: 'Плечи',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['upright row'],
  ),
  ExerciseCatalogItem(
    id: 'face_pull',
    name: 'Тяга к лицу',
    muscleGroup: 'Плечи',
    equipment: 'Кроссовер',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['face pull', 'фейс пул'],
  ),
  ExerciseCatalogItem(
    id: 'rear_delt_machine_fly',
    name: 'Разведение в тренажёре на заднюю дельту',
    muscleGroup: 'Плечи',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['задняя дельта в тренажере', 'rear delt machine fly'],
  ),
  ExerciseCatalogItem(
    id: 'arnold_press',
    name: 'Жим Арнольда',
    muscleGroup: 'Плечи',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['arnold press'],
  ),
  ExerciseCatalogItem(
    id: 'barbell_curl',
    name: 'Подъём штанги на бицепс',
    muscleGroup: 'Бицепс',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['barbell curl'],
  ),
  ExerciseCatalogItem(
    id: 'dumbbell_curl',
    name: 'Подъём гантелей на бицепс',
    muscleGroup: 'Бицепс',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['dumbbell curl'],
  ),
  ExerciseCatalogItem(
    id: 'hammer_curl',
    name: 'Молотки',
    muscleGroup: 'Бицепс',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['hammer curl'],
  ),
  ExerciseCatalogItem(
    id: 'concentration_curl',
    name: 'Концентрированный подъём',
    muscleGroup: 'Бицепс',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['concentration curl'],
  ),
  ExerciseCatalogItem(
    id: 'preacher_curl',
    name: 'Подъём на скамье Скотта',
    muscleGroup: 'Бицепс',
    equipment: 'Скамья Скотта',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['preacher curl'],
  ),
  ExerciseCatalogItem(
    id: 'cable_curl',
    name: 'Подъём в кроссовере',
    muscleGroup: 'Бицепс',
    equipment: 'Кроссовер',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['cable curl'],
  ),
  ExerciseCatalogItem(
    id: 'chin_ups',
    name: 'Подтягивания обратным хватом',
    muscleGroup: 'Бицепс',
    equipment: 'Турник',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['chin ups', 'chin-ups'],
  ),
  ExerciseCatalogItem(
    id: 'french_press',
    name: 'Французский жим',
    muscleGroup: 'Трицепс',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['french press', 'skull crusher'],
  ),
  ExerciseCatalogItem(
    id: 'triceps_pushdown',
    name: 'Разгибание рук на блоке',
    muscleGroup: 'Трицепс',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['pushdown', 'triceps pushdown'],
  ),
  ExerciseCatalogItem(
    id: 'overhead_dumbbell_triceps_extension',
    name: 'Разгибание гантели из-за головы',
    muscleGroup: 'Трицепс',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['overhead dumbbell extension'],
  ),
  ExerciseCatalogItem(
    id: 'close_grip_push_ups',
    name: 'Отжимания узким хватом',
    muscleGroup: 'Трицепс',
    equipment: 'Без оборудования',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['diamond push ups', 'diamond push-ups'],
  ),
  ExerciseCatalogItem(
    id: 'close_grip_bench_press',
    name: 'Жим узким хватом',
    muscleGroup: 'Трицепс',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['close grip bench press'],
  ),
  ExerciseCatalogItem(
    id: 'bench_dips',
    name: 'Обратные отжимания',
    muscleGroup: 'Трицепс',
    equipment: 'Скамья',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['bench dips'],
  ),
  ExerciseCatalogItem(
    id: 'cable_triceps_extension',
    name: 'Разгибание рук в кроссовере',
    muscleGroup: 'Трицепс',
    equipment: 'Кроссовер',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['cable triceps extension'],
  ),
  ExerciseCatalogItem(
    id: 'barbell_squat',
    name: 'Приседания со штангой',
    muscleGroup: 'Ноги',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['squat', 'присед'],
  ),
  ExerciseCatalogItem(
    id: 'front_squat',
    name: 'Фронтальные приседания',
    muscleGroup: 'Ноги',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['front squat'],
  ),
  ExerciseCatalogItem(
    id: 'leg_press',
    name: 'Жим ногами',
    muscleGroup: 'Ноги',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['leg press'],
  ),
  ExerciseCatalogItem(
    id: 'lunges',
    name: 'Выпады',
    muscleGroup: 'Ноги',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['lunges'],
  ),
  ExerciseCatalogItem(
    id: 'bulgarian_split_squat',
    name: 'Болгарские сплит-приседы',
    muscleGroup: 'Ноги',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['болгарские выпады', 'bulgarian split squat'],
  ),
  ExerciseCatalogItem(
    id: 'leg_extension',
    name: 'Разгибание ног в тренажёре',
    muscleGroup: 'Ноги',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['leg extension'],
  ),
  ExerciseCatalogItem(
    id: 'lying_leg_curl',
    name: 'Сгибание ног лёжа',
    muscleGroup: 'Ноги',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['lying leg curl'],
  ),
  ExerciseCatalogItem(
    id: 'glute_bridge',
    name: 'Ягодичный мост',
    muscleGroup: 'Ноги',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['glute bridge'],
  ),
  ExerciseCatalogItem(
    id: 'hip_thrust',
    name: 'Ягодичный мост со штангой',
    muscleGroup: 'Ноги',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['hip thrust', 'хип траст'],
  ),
  ExerciseCatalogItem(
    id: 'stiff_leg_deadlift',
    name: 'Становая тяга на прямых ногах',
    muscleGroup: 'Ноги',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['stiff leg deadlift'],
  ),
  ExerciseCatalogItem(
    id: 'step_ups',
    name: 'Шаги на платформу',
    muscleGroup: 'Ноги',
    equipment: 'Платформа',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['step ups', 'step-ups'],
  ),
  ExerciseCatalogItem(
    id: 'hack_squat',
    name: 'Гакк-присед',
    muscleGroup: 'Ноги',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['hack squat'],
  ),
  ExerciseCatalogItem(
    id: 'smith_machine_squat',
    name: 'Приседания в Смите',
    muscleGroup: 'Ноги',
    equipment: 'Машина Смита',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['smith squat'],
  ),
  ExerciseCatalogItem(
    id: 'sumo_squat',
    name: 'Сумо-присед',
    muscleGroup: 'Ноги',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['sumo squat'],
  ),
  ExerciseCatalogItem(
    id: 'standing_calf_raise',
    name: 'Подъём на носки стоя',
    muscleGroup: 'Икры',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['standing calf raise'],
  ),
  ExerciseCatalogItem(
    id: 'seated_calf_raise',
    name: 'Подъём на носки сидя',
    muscleGroup: 'Икры',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['seated calf raise'],
  ),
  ExerciseCatalogItem(
    id: 'donkey_calf_raise',
    name: 'Ослиные подъёмы на икры',
    muscleGroup: 'Икры',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['donkey calf raise'],
  ),
  ExerciseCatalogItem(
    id: 'crunches',
    name: 'Скручивания',
    muscleGroup: 'Пресс',
    equipment: 'Без оборудования',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['crunches'],
  ),
  ExerciseCatalogItem(
    id: 'reverse_crunches',
    name: 'Обратные скручивания',
    muscleGroup: 'Пресс',
    equipment: 'Без оборудования',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['reverse crunches'],
  ),
  ExerciseCatalogItem(
    id: 'plank',
    name: 'Планка',
    muscleGroup: 'Пресс',
    equipment: 'Без оборудования',
    trackingType: ExerciseTrackingType.duration,
    aliases: ['plank'],
  ),
  ExerciseCatalogItem(
    id: 'side_plank',
    name: 'Боковая планка',
    muscleGroup: 'Пресс',
    equipment: 'Без оборудования',
    trackingType: ExerciseTrackingType.duration,
    aliases: ['side plank'],
  ),
  ExerciseCatalogItem(
    id: 'hanging_leg_raise',
    name: 'Подъём ног в висе',
    muscleGroup: 'Пресс',
    equipment: 'Турник',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['hanging leg raise'],
  ),
  ExerciseCatalogItem(
    id: 'bicycle_crunches',
    name: 'Велосипед',
    muscleGroup: 'Пресс',
    equipment: 'Без оборудования',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['bicycle crunches'],
  ),
  ExerciseCatalogItem(
    id: 'russian_twist',
    name: 'Русские скручивания',
    muscleGroup: 'Пресс',
    equipment: 'Без оборудования',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['russian twist', 'русский твист'],
  ),
  ExerciseCatalogItem(
    id: 'mountain_climbers',
    name: 'Альпинист',
    muscleGroup: 'Пресс',
    equipment: 'Без оборудования',
    trackingType: ExerciseTrackingType.duration,
    aliases: ['mountain climbers'],
  ),
  ExerciseCatalogItem(
    id: 'v_up',
    name: 'Складка',
    muscleGroup: 'Пресс',
    equipment: 'Без оборудования',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['v-up', 'v ups', 'v-ups'],
  ),
  ExerciseCatalogItem(
    id: 'ab_wheel_rollout',
    name: 'Ролик для пресса',
    muscleGroup: 'Пресс',
    equipment: 'Ролик',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['ab wheel', 'ab rollout'],
  ),
  ExerciseCatalogItem(
    id: 'heel_touches',
    name: 'Касания пяток',
    muscleGroup: 'Пресс',
    equipment: 'Без оборудования',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['heel touches'],
  ),
  ExerciseCatalogItem(
    id: 'running',
    name: 'Бег',
    muscleGroup: 'Кардио/функционал',
    equipment: 'Без оборудования',
    trackingType: ExerciseTrackingType.duration,
    aliases: ['run', 'running'],
  ),
  ExerciseCatalogItem(
    id: 'treadmill_walking',
    name: 'Ходьба на дорожке',
    muscleGroup: 'Кардио/функционал',
    equipment: 'Беговая дорожка',
    trackingType: ExerciseTrackingType.duration,
    aliases: ['treadmill walk', 'walking'],
  ),
  ExerciseCatalogItem(
    id: 'exercise_bike',
    name: 'Велотренажёр',
    muscleGroup: 'Кардио/функционал',
    equipment: 'Велотренажёр',
    trackingType: ExerciseTrackingType.duration,
    aliases: ['bike', 'stationary bike'],
  ),
  ExerciseCatalogItem(
    id: 'elliptical',
    name: 'Эллипс',
    muscleGroup: 'Кардио/функционал',
    equipment: 'Эллиптический тренажёр',
    trackingType: ExerciseTrackingType.duration,
    aliases: ['elliptical'],
  ),
  ExerciseCatalogItem(
    id: 'rowing_machine',
    name: 'Гребной тренажёр',
    muscleGroup: 'Кардио/функционал',
    equipment: 'Гребной тренажёр',
    trackingType: ExerciseTrackingType.duration,
    aliases: ['rowing machine', 'rower'],
  ),
  ExerciseCatalogItem(
    id: 'jump_rope',
    name: 'Прыжки на скакалке',
    muscleGroup: 'Кардио/функционал',
    equipment: 'Скакалка',
    trackingType: ExerciseTrackingType.duration,
    aliases: ['jump rope', 'skipping rope'],
  ),
  ExerciseCatalogItem(
    id: 'burpees',
    name: 'Берпи',
    muscleGroup: 'Кардио/функционал',
    equipment: 'Без оборудования',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['burpees'],
  ),
  ExerciseCatalogItem(
    id: 'farmers_walk',
    name: 'Прогулка фермера',
    muscleGroup: 'Кардио/функционал',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.duration,
    aliases: ['farmer’s walk', 'farmer\'s walk'],
  ),
  ExerciseCatalogItem(
    id: 'battle_ropes',
    name: 'Боевые канаты',
    muscleGroup: 'Кардио/функционал',
    equipment: 'Канаты',
    trackingType: ExerciseTrackingType.duration,
    aliases: ['battle ropes'],
  ),
  ExerciseCatalogItem(
    id: 'sled_push',
    name: 'Толкание саней',
    muscleGroup: 'Кардио/функционал',
    equipment: 'Сани',
    trackingType: ExerciseTrackingType.duration,
    aliases: ['sled push'],
  ),
  ExerciseCatalogItem(
    id: 'kettlebell_swing',
    name: 'Махи гирей',
    muscleGroup: 'Кардио/функционал',
    equipment: 'Гиря',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['kettlebell swing'],
  ),
  ExerciseCatalogItem(
    id: 'box_jump',
    name: 'Прыжки на тумбу',
    muscleGroup: 'Кардио/функционал',
    equipment: 'Платформа',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['box jump'],
  ),
];
