import 'exercise_catalog_item.dart';

const List<ExerciseCatalogItem> exerciseCatalog = [
  ExerciseCatalogItem(
    id: 'bench_press_barbell',
    name: 'Жим штанги лёжа',
    muscleGroup: 'Грудь',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['жим лежа', 'bench press'],
  ),
  ExerciseCatalogItem(
    id: 'incline_dumbbell_press',
    name: 'Жим гантелей на наклонной скамье',
    muscleGroup: 'Грудь',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['жим гантелей incline'],
  ),
  ExerciseCatalogItem(
    id: 'push_ups',
    name: 'Отжимания',
    muscleGroup: 'Грудь',
    equipment: 'Без оборудования',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['push ups'],
  ),
  ExerciseCatalogItem(
    id: 'pull_ups',
    name: 'Подтягивания',
    muscleGroup: 'Спина',
    equipment: 'Турник',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['pull ups'],
  ),
  ExerciseCatalogItem(
    id: 'dips',
    name: 'Брусья',
    muscleGroup: 'Трицепс',
    equipment: 'Брусья',
    trackingType: ExerciseTrackingType.bodyweightReps,
    aliases: ['dips'],
  ),
  ExerciseCatalogItem(
    id: 'barbell_squat',
    name: 'Приседания со штангой',
    muscleGroup: 'Ноги',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['squat', 'присед'],
  ),
  ExerciseCatalogItem(
    id: 'leg_press',
    name: 'Жим ногами',
    muscleGroup: 'Ноги',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['leg press'],
  ),
  ExerciseCatalogItem(
    id: 'romanian_deadlift',
    name: 'Румынская тяга',
    muscleGroup: 'Ноги',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['рдл', 'romanian deadlift'],
  ),
  ExerciseCatalogItem(
    id: 'deadlift',
    name: 'Становая тяга',
    muscleGroup: 'Спина',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['deadlift'],
  ),
  ExerciseCatalogItem(
    id: 'lat_pulldown',
    name: 'Тяга верхнего блока',
    muscleGroup: 'Спина',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['lat pulldown'],
  ),
  ExerciseCatalogItem(
    id: 'barbell_row',
    name: 'Тяга штанги в наклоне',
    muscleGroup: 'Спина',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['barbell row'],
  ),
  ExerciseCatalogItem(
    id: 'shoulder_press',
    name: 'Жим над головой',
    muscleGroup: 'Плечи',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['overhead press', 'ohp'],
  ),
  ExerciseCatalogItem(
    id: 'lateral_raise',
    name: 'Разведения гантелей в стороны',
    muscleGroup: 'Плечи',
    equipment: 'Гантели',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['lateral raise'],
  ),
  ExerciseCatalogItem(
    id: 'barbell_curl',
    name: 'Подъём штанги на бицепс',
    muscleGroup: 'Бицепс',
    equipment: 'Штанга',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['barbell curl'],
  ),
  ExerciseCatalogItem(
    id: 'triceps_pushdown',
    name: 'Разгибание рук на блоке',
    muscleGroup: 'Трицепс',
    equipment: 'Тренажёр',
    trackingType: ExerciseTrackingType.weightReps,
    aliases: ['pushdown', 'triceps pushdown'],
  ),
  ExerciseCatalogItem(
    id: 'plank',
    name: 'Планка',
    muscleGroup: 'Пресс',
    equipment: 'Без оборудования',
    trackingType: ExerciseTrackingType.duration,
    aliases: ['plank'],
  ),
  ExerciseCatalogItem(
    id: 'side_plank',
    name: 'Боковая планка',
    muscleGroup: 'Пресс',
    equipment: 'Без оборудования',
    trackingType: ExerciseTrackingType.duration,
    aliases: ['side plank'],
  ),
];