// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCksLxhXP12DmDs9-vp2bNYvlpgb6hv33E',
    appId: '1:1078850156060:web:1096958de4be35c23791d9',
    messagingSenderId: '1078850156060',
    projectId: 'grindstone-a581e',
    authDomain: 'grindstone-a581e.firebaseapp.com',
    storageBucket: 'grindstone-a581e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmjhNktpuXPn2WVgB0fyLxbbsrCgTpJZI',
    appId: '1:361665547460:android:8ba64b85965a38e2354d91',
    messagingSenderId: '361665547460',
    projectId: 'grindstone-8be1a',
    storageBucket: 'grindstone-8be1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAPmNPtvKLXRlVAESv2qiOIbm93K2TbTY',
    appId: '1:1078850156060:ios:35724e7ae3c5fe3d3791d9',
    messagingSenderId: '1078850156060',
    projectId: 'grindstone-a581e',
    storageBucket: 'grindstone-a581e.firebasestorage.app',
    iosBundleId: 'com.example.dp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAPmNPtvKLXRlVAESv2qiOIbm93K2TbTY',
    appId: '1:1078850156060:ios:35724e7ae3c5fe3d3791d9',
    messagingSenderId: '1078850156060',
    projectId: 'grindstone-a581e',
    storageBucket: 'grindstone-a581e.firebasestorage.app',
    iosBundleId: 'com.example.dp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCksLxhXP12DmDs9-vp2bNYvlpgb6hv33E',
    appId: '1:1078850156060:web:fe8a6b141a6a06db3791d9',
    messagingSenderId: '1078850156060',
    projectId: 'grindstone-a581e',
    authDomain: 'grindstone-a581e.firebaseapp.com',
    storageBucket: 'grindstone-a581e.firebasestorage.app',
  );
}